CREATE DATABASE IF NOT EXISTS auto_reencauches CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;

CREATE TABLE CLIENTE(
    id  				INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nombre 				VARCHAR(100) NOT NULL,
    apellido			VARCHAR(100) NOT NULL,
    cedula				BIGINT NOT NULL,
    telefono			BIGINT NOT NULL,
    email				VARCHAR(100) NOT NULL
);

ALTER TABLE CLIENTE ADD CONSTRAINT KEY_U_CLIENTE UNIQUE(cedula,telefono,email,usuario);

ALTER TABLE CLIENTE ADD CONSTRAINT KEY_U_PROVEEDOR_CEDULA UNIQUE(cedula);
ALTER TABLE CLIENTE ADD CONSTRAINT KEY_U_CLIENTE_TELEFONO UNIQUE(telefono);
ALTER TABLE CLIENTE ADD CONSTRAINT KEY_U_CLIENTE_EMAIL UNIQUE(email);

CREATE TABLE PROVEEDOR(
    id  				INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nit					VARCHAR(100) NOT NULL,
    nombre 				VARCHAR(100) NOT NULL,
    telefono			BIGINT NOT NULL,
    direccion			VARCHAR(100) NOT NULL
);

ALTER TABLE PROVEEDOR ADD CONSTRAINT KEY_U_PROVEEDOR_NIT UNIQUE(nit);
ALTER TABLE PROVEEDOR ADD CONSTRAINT KEY_U_PROVEEDOR_TELEFONO UNIQUE(telefono);


CREATE TABLE INICIAR_SESION(
    id  				INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    cedula				BIGINT NOT NULL,
	usuario				VARCHAR(100) NOT NULL,
    password			VARCHAR(100) NOT NULL,
    repeat_password 	VARCHAR(100) NOT NULL,
    rol 				VARCHAR(100) NOT NULL,
    veces_iniciada		INTEGER NOT NULL DEFAULT 0
);


ALTER TABLE INICIAR_SESION ADD CONSTRAINT KEY_U_INICIAR_SESION_USUARIO UNIQUE(usuario);
ALTER TABLE INICIAR_SESION ADD CONSTRAINT KEY_F_INICIAR_SESION_CLIENTE_CEDULA FOREIGN KEY (cedula) REFERENCES CLIENTE (cedula)

CREATE TABLE PRODUCTO{
	id					INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	nombre_prod			VARCHAR(100) NOT NULL,
	marca_prod			VARCHAR(100) NOT NULL,
	nit_prov			VARCHAR(100) NOT NULL,
	logo_prod			VARCHAR(100) NOT NULL,
	imagen_prod			VARCHAR(100) NOT NULL,
	descripcion_prod	VARCHAR(300) NOT NULL,
	beneficios_prod		VARCHAR(300) NOT NULL,
	precio_prod			INTEGER NOT NULL,
	cantidad_ex_prod	INTEGER NOT NULL,
	peso_prod			INTEGER NOT NULL,
	peso_unidad			VARCHAR(100) NOT NULL,
	ancho_prod			INTEGER NOT NULL,
	perfil_prod			INTEGER NOT NULL,
	rin_prod			DOUBLE NOT NULL,
	eje_prod			VARCHAR(100) NOT NULL,
	terreno_prod		VARCHAR(100) NOT NULL,
	tipo_prod 			VARCHAR(100) NOT NULL,
	vehiculo			VARCHAR(100) NOT NULL
);

ALTER TABLE PRODUCTO ADD CONSTRAINT KEY_U_PRODUCTO_NOMBRE UNIQUE(nombre_prod);
ALTER TABLE PRODUCTO ADD CONSTRAINT KEY_F_PRODUCTO_PROVEEDOR_NIT FOREIGN KEY(nit_prov) REFERENCES PROVEEDOR(nit);







  
  
  
    

  

